// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/foreman": {
    params: {};
  };
  "/dashboard/crew": {
    params: {};
  };
  "/tools": {
    params: {};
  };
  "/materials": {
    params: {};
  };
  "/projects": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/dashboard" | "/dashboard/foreman" | "/dashboard/crew";
    page: "/" | "/login" | "/tools" | "/materials" | "/projects";
  };
  "./routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "./routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "./routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "./routes/dashboard.foreman.tsx": {
    id: "routes/dashboard.foreman";
    page: "/dashboard/foreman";
  };
  "./routes/dashboard.crew.tsx": {
    id: "routes/dashboard.crew";
    page: "/dashboard/crew";
  };
  "./routes/tools.tsx": {
    id: "routes/tools";
    page: "/tools";
  };
  "./routes/materials.tsx": {
    id: "routes/materials";
    page: "/materials";
  };
  "./routes/projects.tsx": {
    id: "routes/projects";
    page: "/projects";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/./routes/_index.tsx");
  "routes/login": typeof import("./app/./routes/login.tsx");
  "routes/dashboard": typeof import("./app/./routes/dashboard.tsx");
  "routes/dashboard.foreman": typeof import("./app/./routes/dashboard.foreman.tsx");
  "routes/dashboard.crew": typeof import("./app/./routes/dashboard.crew.tsx");
  "routes/tools": typeof import("./app/./routes/tools.tsx");
  "routes/materials": typeof import("./app/./routes/materials.tsx");
  "routes/projects": typeof import("./app/./routes/projects.tsx");
};